Squirrel.create(name: "Sandy")
Squirrel.create(name: "Rocky")
Squirrel.create(name: "Secret")

Tree.create(height_in_ft: 70, tree_type: "maple")
Tree.create(height_in_ft: 360, tree_type: "redwood")
Tree.create(height_in_ft: 75, tree_type: "mahogany")

SquirrelTree.create(name: "sadhfdsahf", squirrel_id: 1, tree_id: 1)
SquirrelTree.create(name: "reqouhfjkqel", squirrel_id: 1, tree_id: 2)
SquirrelTree.create(name: "reiuhflwefhjwlq", squirrel_id: 1, tree_id: 3)
SquirrelTree.create(name: "euhwqfilqjiq3", squirrel_id: 2, tree_id: 1)
SquirrelTree.create(name: "eqwiufwel", squirrel_id: 2, tree_id: 2)
SquirrelTree.create(name: "vqeklvbjel", squirrel_id: 2, tree_id: 3)
SquirrelTree.create(name: "bvueitrvter", squirrel_id: 3, tree_id: 1)
SquirrelTree.create(name: "reiowhflewrfn2", squirrel_id: 3, tree_id: 2)
SquirrelTree.create(name: "fheiclqnj3l1c", squirrel_id: 3, tree_id: 3)